mode: auto

avatar:
  url: https://avatars.githubusercontent.com/u/92374733?s=400&u=9acc95d2b39d9a08e9edbef553e9dcac29e801ba&v=4
  status:
    enable: true
    emoji: ğŸƒ
    message: é£å¹å¶è½

reward:
  enable: false

comment:
  enable: true
  candidates:
    - giscus

giscus:
  enable: true
  repo: By-Seayay/Blog
  repo-id: R_kgDOKjR0PQ
  category: Giscus
  category-id: DIC_kwDOKjR0Pc4CaVPi
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: preferred_color_scheme

footer:
  since: 2022

post_edit:
  enable: true
  url: https://github.com/By-Seayay/Blog/tree/master/source/

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ion:md-bookmarks
    color: dodgerblue

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

cursor:
  enable: true

say:
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn?c=a&c=c